version: '3.8'

services:
  mysqlsrv:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "developer"
      MYSQL_DATABASE: "devdb"
    ports:
      - "3307:3306"  # Mapeia a porta 3307 do host para a porta 3306 do contêiner
    volumes:
      - /data/mysql:/var/lib/mysql
    networks:
      - dev-rede

  adminer:
    image: adminer
    ports:
      - "8080:8080"  # Assegure-se de usar aspas para consistência
    networks:
      - dev-rede

networks:
  dev-rede:
    driver: bridge



//// 



version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: