version: '3.8'

services:
  oracledb:
    image: container-registry.oracle.com/database/enterprise:19.3.0.0
    container_name: oracledb
    environment:
      ORACLE_SID: dev
      ORACLE_PDB: PDB1
      ORACLE_PWD: developer
      ORACLE_CHARACTERSET: AL32UTF8
    ports:
      - "1521:1521"  # Porta para acessar o banco de dados
      - "5500:5500"  # Porta para acessar o Enterprise Manager (opcional)
    volumes:
      - oracle-data:/opt/oracle/oradata
      - ./dumps:/opt/oracle/dumps  # Mapeamento de volume para dumps
    networks:
      - oraclenet

volumes:
  oracle-data:
    driver: local

networks:
  oraclenet:
    driver: bridge



sqlplus sys/developer@dev as sysdba



CREATE TABLESPACE desenv
DATAFILE '/opt/oracle/oradata/ORCLCDB/desenv.dbf'DATAFILE '/opt/oracle/oradata/ORCLCDB/desenv.dbf'

SIZE 30GB
AUTOEXTEND ON
NEXT 10M MAXSIZE UNLIMITED;


impdp dbteste/developer@dev directory=DATA_PUMP_DIR dumpfile=f.dmp logfile=import.log


scp f.dmp adriley@192.168.1.17:/desenvolvimento/dumps/

Esse funciona 

CREATE TABLESPACE app
DATAFILE '/opt/oracle/oradata/DEV/app.dbf'
SIZE 5G
AUTOEXTEND ON
NEXT 1G;